// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommodityItem: typeof import('./src/components/CommodityItem.vue')['default']
    FloatButton: typeof import('./src/components/FloatButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopColor: typeof import('./src/components/TopColor.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    VanPicker: typeof import('vant/es')['Picker']
    VanSlider: typeof import('vant/es')['Slider']
    WelcomeInfo: typeof import('./src/components/WelcomeInfo.vue')['default']
  }
}
